### ISSUE TITLE
Řešení 1

### ISSUE THREAD

**Issue by crabhi** [2016-molinf/jirka#1]
Ahoj,
řešení je pěkné, zadání splňuje a líbí se mi, že děláš validaci vstupního vzorce. Co se ale stane, když udělám `Molecule("B-52 a nějaká další blbost")`?

Jedna rada (zase mimo zadání) - kód se zjednoduší a zrychlí, když metody pracují nad nějakou vnitřní reprezentací, ne nad stringem. Třeba dict symbol -> počet. Takhle musí všechny metody pracovat s regulárními výrazy. To se týká i těch hmotností. Ten soubor se nemusí načítat pro každou molekulu znovu. Ale pro toto zadání je to naprosto OK.

**Comment by gorgitko** [comment]
Ahoj,

jak se říká: práce kvapná, málo platná :) Ty věci, o kterých píšeš, mě napadly v průběhu psaní, ale chtěl jsem to mít hotové do konce hodiny. Takže jsem to teď ještě upravil.

**Comment by crabhi** [comment]
Pěkné. :-)
